/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Layout_evolutionRouteImport } from './routes/_layout_evolution'
import { Route as Layout_demoRouteImport } from './routes/_layout_demo'
import { Route as Layout_autoresearchRouteImport } from './routes/_layout_autoresearch'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Layout_evolutionEvolutionRouteImport } from './routes/_layout_evolution/evolution'
import { Route as Layout_demoDemoRouteImport } from './routes/_layout_demo/demo'
import { Route as Layout_autoresearchAutoresearchRouteImport } from './routes/_layout_autoresearch/autoresearch'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutMemoryRouteImport } from './routes/_layout/memory'
import { Route as LayoutLlm_roviderRouteImport } from './routes/_layout/llm_rovider'
import { Route as LayoutLiveCodesRouteImport } from './routes/_layout/live-codes'
import { Route as LayoutGuideRouteImport } from './routes/_layout/guide'
import { Route as LayoutFeedbackRouteImport } from './routes/_layout/feedback'
import { Route as LayoutConfig_templateRouteImport } from './routes/_layout/config_template'
import { Route as LayoutChangelogRouteImport } from './routes/_layout/changelog'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Layout_evolutionRoute = Layout_evolutionRouteImport.update({
  id: '/_layout_evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const Layout_demoRoute = Layout_demoRouteImport.update({
  id: '/_layout_demo',
  getParentRoute: () => rootRouteImport,
} as any)
const Layout_autoresearchRoute = Layout_autoresearchRouteImport.update({
  id: '/_layout_autoresearch',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Layout_evolutionEvolutionRoute =
  Layout_evolutionEvolutionRouteImport.update({
    id: '/evolution',
    path: '/evolution',
    getParentRoute: () => Layout_evolutionRoute,
  } as any)
const Layout_demoDemoRoute = Layout_demoDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => Layout_demoRoute,
} as any)
const Layout_autoresearchAutoresearchRoute =
  Layout_autoresearchAutoresearchRouteImport.update({
    id: '/autoresearch',
    path: '/autoresearch',
    getParentRoute: () => Layout_autoresearchRoute,
  } as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMemoryRoute = LayoutMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLlm_roviderRoute = LayoutLlm_roviderRouteImport.update({
  id: '/llm_rovider',
  path: '/llm_rovider',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLiveCodesRoute = LayoutLiveCodesRouteImport.update({
  id: '/live-codes',
  path: '/live-codes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGuideRoute = LayoutGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeedbackRoute = LayoutFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfig_templateRoute = LayoutConfig_templateRouteImport.update({
  id: '/config_template',
  path: '/config_template',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChangelogRoute = LayoutChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/changelog': typeof LayoutChangelogRoute
  '/config_template': typeof LayoutConfig_templateRoute
  '/feedback': typeof LayoutFeedbackRoute
  '/guide': typeof LayoutGuideRoute
  '/live-codes': typeof LayoutLiveCodesRoute
  '/llm_rovider': typeof LayoutLlm_roviderRoute
  '/memory': typeof LayoutMemoryRoute
  '/projects': typeof LayoutProjectsRoute
  '/settings': typeof LayoutSettingsRoute
  '/autoresearch': typeof Layout_autoresearchAutoresearchRoute
  '/demo': typeof Layout_demoDemoRoute
  '/evolution': typeof Layout_evolutionEvolutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/changelog': typeof LayoutChangelogRoute
  '/config_template': typeof LayoutConfig_templateRoute
  '/feedback': typeof LayoutFeedbackRoute
  '/guide': typeof LayoutGuideRoute
  '/live-codes': typeof LayoutLiveCodesRoute
  '/llm_rovider': typeof LayoutLlm_roviderRoute
  '/memory': typeof LayoutMemoryRoute
  '/projects': typeof LayoutProjectsRoute
  '/settings': typeof LayoutSettingsRoute
  '/autoresearch': typeof Layout_autoresearchAutoresearchRoute
  '/demo': typeof Layout_demoDemoRoute
  '/evolution': typeof Layout_evolutionEvolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout_autoresearch': typeof Layout_autoresearchRouteWithChildren
  '/_layout_demo': typeof Layout_demoRouteWithChildren
  '/_layout_evolution': typeof Layout_evolutionRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/changelog': typeof LayoutChangelogRoute
  '/_layout/config_template': typeof LayoutConfig_templateRoute
  '/_layout/feedback': typeof LayoutFeedbackRoute
  '/_layout/guide': typeof LayoutGuideRoute
  '/_layout/live-codes': typeof LayoutLiveCodesRoute
  '/_layout/llm_rovider': typeof LayoutLlm_roviderRoute
  '/_layout/memory': typeof LayoutMemoryRoute
  '/_layout/projects': typeof LayoutProjectsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout_autoresearch/autoresearch': typeof Layout_autoresearchAutoresearchRoute
  '/_layout_demo/demo': typeof Layout_demoDemoRoute
  '/_layout_evolution/evolution': typeof Layout_evolutionEvolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin'
    | '/changelog'
    | '/config_template'
    | '/feedback'
    | '/guide'
    | '/live-codes'
    | '/llm_rovider'
    | '/memory'
    | '/projects'
    | '/settings'
    | '/autoresearch'
    | '/demo'
    | '/evolution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin'
    | '/changelog'
    | '/config_template'
    | '/feedback'
    | '/guide'
    | '/live-codes'
    | '/llm_rovider'
    | '/memory'
    | '/projects'
    | '/settings'
    | '/autoresearch'
    | '/demo'
    | '/evolution'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout_autoresearch'
    | '/_layout_demo'
    | '/_layout_evolution'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_layout/admin'
    | '/_layout/changelog'
    | '/_layout/config_template'
    | '/_layout/feedback'
    | '/_layout/guide'
    | '/_layout/live-codes'
    | '/_layout/llm_rovider'
    | '/_layout/memory'
    | '/_layout/projects'
    | '/_layout/settings'
    | '/_layout_autoresearch/autoresearch'
    | '/_layout_demo/demo'
    | '/_layout_evolution/evolution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  Layout_autoresearchRoute: typeof Layout_autoresearchRouteWithChildren
  Layout_demoRoute: typeof Layout_demoRouteWithChildren
  Layout_evolutionRoute: typeof Layout_evolutionRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout_evolution': {
      id: '/_layout_evolution'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Layout_evolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout_demo': {
      id: '/_layout_demo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Layout_demoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout_autoresearch': {
      id: '/_layout_autoresearch'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Layout_autoresearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout_evolution/evolution': {
      id: '/_layout_evolution/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof Layout_evolutionEvolutionRouteImport
      parentRoute: typeof Layout_evolutionRoute
    }
    '/_layout_demo/demo': {
      id: '/_layout_demo/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof Layout_demoDemoRouteImport
      parentRoute: typeof Layout_demoRoute
    }
    '/_layout_autoresearch/autoresearch': {
      id: '/_layout_autoresearch/autoresearch'
      path: '/autoresearch'
      fullPath: '/autoresearch'
      preLoaderRoute: typeof Layout_autoresearchAutoresearchRouteImport
      parentRoute: typeof Layout_autoresearchRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/memory': {
      id: '/_layout/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof LayoutMemoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/llm_rovider': {
      id: '/_layout/llm_rovider'
      path: '/llm_rovider'
      fullPath: '/llm_rovider'
      preLoaderRoute: typeof LayoutLlm_roviderRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/live-codes': {
      id: '/_layout/live-codes'
      path: '/live-codes'
      fullPath: '/live-codes'
      preLoaderRoute: typeof LayoutLiveCodesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/guide': {
      id: '/_layout/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof LayoutGuideRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/feedback': {
      id: '/_layout/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof LayoutFeedbackRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/config_template': {
      id: '/_layout/config_template'
      path: '/config_template'
      fullPath: '/config_template'
      preLoaderRoute: typeof LayoutConfig_templateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/changelog': {
      id: '/_layout/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof LayoutChangelogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutChangelogRoute: typeof LayoutChangelogRoute
  LayoutConfig_templateRoute: typeof LayoutConfig_templateRoute
  LayoutFeedbackRoute: typeof LayoutFeedbackRoute
  LayoutGuideRoute: typeof LayoutGuideRoute
  LayoutLiveCodesRoute: typeof LayoutLiveCodesRoute
  LayoutLlm_roviderRoute: typeof LayoutLlm_roviderRoute
  LayoutMemoryRoute: typeof LayoutMemoryRoute
  LayoutProjectsRoute: typeof LayoutProjectsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutChangelogRoute: LayoutChangelogRoute,
  LayoutConfig_templateRoute: LayoutConfig_templateRoute,
  LayoutFeedbackRoute: LayoutFeedbackRoute,
  LayoutGuideRoute: LayoutGuideRoute,
  LayoutLiveCodesRoute: LayoutLiveCodesRoute,
  LayoutLlm_roviderRoute: LayoutLlm_roviderRoute,
  LayoutMemoryRoute: LayoutMemoryRoute,
  LayoutProjectsRoute: LayoutProjectsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface Layout_autoresearchRouteChildren {
  Layout_autoresearchAutoresearchRoute: typeof Layout_autoresearchAutoresearchRoute
}

const Layout_autoresearchRouteChildren: Layout_autoresearchRouteChildren = {
  Layout_autoresearchAutoresearchRoute: Layout_autoresearchAutoresearchRoute,
}

const Layout_autoresearchRouteWithChildren =
  Layout_autoresearchRoute._addFileChildren(Layout_autoresearchRouteChildren)

interface Layout_demoRouteChildren {
  Layout_demoDemoRoute: typeof Layout_demoDemoRoute
}

const Layout_demoRouteChildren: Layout_demoRouteChildren = {
  Layout_demoDemoRoute: Layout_demoDemoRoute,
}

const Layout_demoRouteWithChildren = Layout_demoRoute._addFileChildren(
  Layout_demoRouteChildren,
)

interface Layout_evolutionRouteChildren {
  Layout_evolutionEvolutionRoute: typeof Layout_evolutionEvolutionRoute
}

const Layout_evolutionRouteChildren: Layout_evolutionRouteChildren = {
  Layout_evolutionEvolutionRoute: Layout_evolutionEvolutionRoute,
}

const Layout_evolutionRouteWithChildren =
  Layout_evolutionRoute._addFileChildren(Layout_evolutionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  Layout_autoresearchRoute: Layout_autoresearchRouteWithChildren,
  Layout_demoRoute: Layout_demoRouteWithChildren,
  Layout_evolutionRoute: Layout_evolutionRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
